version: '3.8'
services:
  app:
    container_name: account_book_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - app_network
networks:
  app_network:
    external: true