spring:
  application:
    name: AccountBook
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/accountbook
      username: accountbook
      password: accountbook1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:/mapper/*.xml